command:
  - python3.9
  - ${program}
  - ${args_no_boolean_flags}
entity: 
method: random
name: IQL (Unifloral)
program: algorithms/unifloral.py
project: unifloral

parameters:
  # --- Experiment ---
  seed:
    values: [0, 1, 2, 3, 4]
  dataset:
    values:
      - halfcheetah-medium-v2
  algorithm:
    value: unifloral_iql
  num_updates:
    value: 1_000_000
  eval_interval:
    value: 2500
  eval_workers:
    value: 8
  eval_final_episodes:
    value: 1000

  # --- Logging ---
  log:
    value: true
  wandb_project:
    value: unifloral
  wandb_team:
    value: pablo_samuel-castro
  wandb_group:
    value: debug

  # --- Generic optimization ---
  lr:
    value: 3e-4
  actor_lr:
    value: 3e-4
  lr_schedule:
    value: cosine
  batch_size:
    value: 256
  gamma:
    value: 0.99
  polyak_step_size:
    value: 0.005
  norm_obs:
    value: true

  # --- Actor architecture ---
  actor_num_layers:
    value: 2
  actor_layer_width:
    value: 256
  actor_ln:
    value: false
  deterministic:
    value: false
  deterministic_eval:
    value: true
  use_tanh_mean:
    value: true
  use_log_std_param:
    value: true
  log_std_min:
    value: -20.0
  log_std_max:
    value: 2.0

  # --- Critic + value function architecture ---
  num_critics:
    value: 2
  critic_num_layers:
    value: 2
  critic_layer_width:
    value: 256
  critic_ln:
    value: false

  # --- Actor loss components ---
  actor_bc_coef:
    value: 1.0  # Weight of AWR loss
  actor_q_coef:
    value: 0.0
  use_q_target_in_actor:
    value: false
  normalize_q_loss:
    value: false
  aggregate_q:
    value: min

  # --- AWR (Advantage Weighted Regression) actor ---
  use_awr:
    value: true
  awr_temperature:
    value: [0.5, 3.0, 10.0]  # IQL beta
  awr_exp_adv_clip:
    value: 100.0

  # --- Critic loss components ---
  num_critic_updates_per_step:
    value: 1
  critic_bc_coef:
    value: 0.0
  diversity_coef:
    value: 0.0
  policy_noise:
    value: 0.0
  noise_clip:
    value: 0.0
  use_target_actor:
    value: false

  # --- Value function ---
  use_value_target:
    value: false
  value_expectile:
    value: [0.5, 0.7, 0.9]  # IQL tau

  # --- Entropy loss ---
  use_entropy_loss:
    value: false
  ent_coef_init:
    value: 1.0
  actor_entropy_coef:
    value: 0.0
  critic_entropy_coef:
    value: 0.0