command:
  - python3.9
  - ${program}
  - ${args_no_boolean_flags}
entity: pablo_samuel-castro
method: random
name: COMBO
program: algorithms/combo.py
project: unifloral

parameters:
  # --- Experiment ---
  seed:
    value: 0  # Fixed seed since we're sweeping over models
  dataset:
    values:
      - halfcheetah-medium-v2
  algorithm:
    value: combo
  num_updates:
    value: 3000000
  eval_interval:
    value: 2500
  eval_workers:
    value: 8
  eval_final_episodes:
    value: 1000

  # --- Logging ---
  log:
    value: true
  wandb_project:
    value: unifloral
  wandb_team:
    value: flair
  wandb_group:
    value: debug

  # --- Generic optimization ---
  lr:
    values:
      - 1e-4
      - 3e-4
  batch_size:
    value: 256
  gamma:
    value: 0.99
  polyak_step_size:
    value: 0.005

  # --- Model-based specific ---
  model_path:
    values:  # This will be replaced with actual model paths for each environment
      - "PLACEHOLDER_MODEL_PATH"
  model_retain_epochs:
    value: 5
  num_critics:
    value: 10
  rollout_batch_size:
    value: 50000
  rollout_interval:
    value: 1000
  rollout_length:
    values: [1, 5, 25]
  dataset_sample_ratio:
    values: [0.5, 0.8]

  # --- CQL ---
  actor_lr:
    values: [1e-5, 3e-5, 1e-4]
  cql_temperature:
    value: 1.0
  cql_min_q_weight:
    values: [0.5, 1.0, 5.0]